import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'gown',
  title: 'Gowns',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identity', default: true },
    { name: 'photography', title: 'Photography' },
    { name: 'facts', title: 'Verified facts' },
    { name: 'publishing', title: 'Publishing' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Gown Name',
      type: 'string',
      group: 'identity',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      group: 'identity',
      description: 'Stable gown id in the URL. Independent of photo folder layout.',
      options: { source: 'name', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'nameStatus',
      title: 'Name verification',
      type: 'string',
      group: 'identity',
      options: {
        list: [
          { title: 'Confirmed — may appear as a public fact', value: 'confirmed' },
          { title: 'Needs review', value: 'needs-review' },
          { title: 'Draft', value: 'draft' },
        ],
        layout: 'radio',
      },
      initialValue: 'needs-review',
    }),
    defineField({
      name: 'designer',
      title: 'Designer',
      type: 'reference',
      group: 'identity',
      to: [{ type: 'designer' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'catalogueImages',
      title: 'Photography',
      group: 'photography',
      description:
        'One gown record, many image references. Classify type only when it can actually be established. Incomplete gowns may have no images.',
      type: 'array',
      of: [{ type: 'gownImage' }],
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'verifiedString',
      group: 'facts',
      description: 'wedding / bridesmaid / occasion — only confirmed values appear publicly.',
    }),
    defineField({
      name: 'styleCode',
      title: 'Style code',
      type: 'verifiedString',
      group: 'facts',
    }),
    defineField({
      name: 'sizes',
      title: 'Sizes',
      type: 'verifiedStringList',
      group: 'facts',
      description: 'e.g. UK 14. Leave empty rather than guessing.',
    }),
    defineField({
      name: 'silhouette',
      title: 'Silhouette',
      type: 'verifiedString',
      group: 'facts',
    }),
    defineField({
      name: 'style',
      title: 'Style tags',
      type: 'verifiedStringList',
      group: 'facts',
    }),
    defineField({
      name: 'fabric',
      title: 'Fabric',
      type: 'verifiedString',
      group: 'facts',
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'verifiedString',
      group: 'facts',
    }),
    defineField({
      name: 'availability',
      title: 'Availability',
      type: 'verifiedString',
      group: 'facts',
      description: 'Factual stock/sample status. Separate from whether the gown is listed on the site.',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'verifiedText',
      group: 'facts',
    }),
    defineField({
      name: 'isNew',
      title: 'New Arrival?',
      group: 'publishing',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured on Homepage?',
      group: 'publishing',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'available',
      title: 'Listed on website?',
      group: 'publishing',
      description: 'Uncheck to hide this gown. Incomplete records may still be listed.',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'image',
      title: 'Main Image (legacy)',
      type: 'image',
      hidden: true,
    }),
    defineField({
      name: 'images',
      title: 'Additional Images (legacy)',
      type: 'array',
      of: [{ type: 'image' }],
      hidden: true,
    }),
    defineField({
      name: 'priceRange',
      title: 'Price range (legacy)',
      type: 'string',
      hidden: true,
    }),
    defineField({
      name: 'features',
      title: 'Features (legacy)',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: true,
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'designer.name',
      media: 'catalogueImages.0.image',
      legacy: 'image',
    },
    prepare({ title, subtitle, media, legacy }) {
      return {
        title: title || 'Untitled gown',
        subtitle: subtitle || 'No designer',
        media: media || legacy,
      };
    },
  },
});
